<?php
// admin-panel.php
session_start();
if(!isset($_SESSION['admin']) || $_SESSION['admin'] !== true){
    header("Location: admin-login.php");
        exit();
        }
        require_once 'config.php';

        // عملیات بن کردن و رفع بن
        if(isset($_GET['ban']) && is_numeric($_GET['ban'])){
            $user_id = intval($_GET['ban']);
                $stmt = $conn->prepare("UPDATE users SET is_banned = 1 WHERE id = ?");
                    $stmt->bind_param("i", $user_id);
                        $stmt->execute();
                            $stmt->close();
                                header("Location: admin-panel.php");
                                    exit();
                                    }
                                    if(isset($_GET['unban']) && is_numeric($_GET['unban'])){
                                        $user_id = intval($_GET['unban']);
                                            $stmt = $conn->prepare("UPDATE users SET is_banned = 0 WHERE id = ?");
                                                $stmt->bind_param("i", $user_id);
                                                    $stmt->execute();
                                                        $stmt->close();
                                                            header("Location: admin-panel.php");
                                                                exit();
                                                                }

                                                                // عملیات حذف پست
                                                                if(isset($_GET['deletePost']) && is_numeric($_GET['deletePost'])){
                                                                    $post_id = intval($_GET['deletePost']);
                                                                        // حذف فایل از سرور (در صورت وجود)
                                                                            $stmt = $conn->prepare("SELECT media FROM posts WHERE id = ?");
                                                                                $stmt->bind_param("i", $post_id);
                                                                                    $stmt->execute();
                                                                                        $stmt->bind_result($mediaFile);
                                                                                            if($stmt->fetch()){
                                                                                                    if(file_exists($mediaFile)){
                                                                                                                unlink($mediaFile);
                                                                                                                        }
                                                                                                                            }
                                                                                                                                $stmt->close();
                                                                                                                                    // حذف پست از دیتابیس
                                                                                                                                        $stmt = $conn->prepare("DELETE FROM posts WHERE id = ?");
                                                                                                                                            $stmt->bind_param("i", $post_id);
                                                                                                                                                $stmt->execute();
                                                                                                                                                    $stmt->close();
                                                                                                                                                        header("Location: admin-panel.php");
                                                                                                                                                            exit();
                                                                                                                                                            }

                                                                                                                                                            // دریافت کاربران
                                                                                                                                                            $usersResult = $conn->query("SELECT * FROM users");
                                                                                                                                                            // دریافت پست‌ها
                                                                                                                                                            $postsResult = $conn->query("SELECT posts.*, users.username FROM posts JOIN users ON posts.user_id = users.id ORDER BY created_at DESC");
                                                                                                                                                            ?>
                                                                                                                                                            <!DOCTYPE html>
                                                                                                                                                            <html lang="fa">
                                                                                                                                                            <head>
                                                                                                                                                                <meta charset="UTF-8">
                                                                                                                                                                    <title>پنل مدیریت</title>
                                                                                                                                                                        <link rel="stylesheet" href="style.css">
                                                                                                                                                                            <meta name="viewport" content="width=device-width, initial-scale=1">
                                                                                                                                                                                <style>
                                                                                                                                                                                    /* استایل سریع برای منوی همبرگری (در صورت نیاز) */
                                                                                                                                                                                        .hamburger {
                                                                                                                                                                                                display: none;
                                                                                                                                                                                                        cursor: pointer;
                                                                                                                                                                                                            }
                                                                                                                                                                                                                .bar {
                                                                                                                                                                                                                        display: block;
                                                                                                                                                                                                                                width: 25px;
                                                                                                                                                                                                                                        height: 3px;
                                                                                                                                                                                                                                                margin: 5px auto;
                                                                                                                                                                                                                                                        transition: all 0.3s ease-in-out;
                                                                                                                                                                                                                                                                background-color: #333;
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                        @media (max-width: 600px) {
                                                                                                                                                                                                                                                                              .hamburger { display: block; }
                                                                                                                                                                                                                                                                                    .nav-links { display: none; }
                                                                                                                                                                                                                                                                                          .nav-links.active { display: block; text-align: center; }
                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                  </style>
                                                                                                                                                                                                                                                                                                  </head>
                                                                                                                                                                                                                                                                                                  <body>
                                                                                                                                                                                                                                                                                                      <nav class="navbar">
                                                                                                                                                                                                                                                                                                              <div class="logo">پنل مدیریت</div>
                                                                                                                                                                                                                                                                                                                      <div class="hamburger" onclick="toggleMenu()">
                                                                                                                                                                                                                                                                                                                                  <span class="bar"></span>
                                                                                                                                                                                                                                                                                                                                              <span class="bar"></span>
                                                                                                                                                                                                                                                                                                                                                          <span class="bar"></span>
                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                          <div class="nav-links">
                                                                                                                                                                                                                                                                                                                                                                                      <a href="home.php">خانه</a>
                                                                                                                                                                                                                                                                                                                                                                                                  <a href="logout.php">خروج</a>
                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                              </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="container">
                                                                                                                                                                                                                                                                                                                                                                                                                              <h2>مدیریت کاربران</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <th>آی دی</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <th>نام کاربری</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <th>ایمیل</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <th>وضعیت بن</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <th>عملیات</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <?php while($row = $usersResult->fetch_assoc()): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td><?php echo $row['id']; ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td><?php echo htmlspecialchars($row['username']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td><?php echo htmlspecialchars($row['email']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td><?php echo $row['is_banned'] ? 'بن شده' : 'عادی'; ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <?php if($row['is_banned'] == 0): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <a href="admin-panel.php?ban=<?php echo $row['id']; ?>">بن کن</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href="admin-panel.php?unban=<?php echo $row['id']; ?>">رفع بن</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2>مدیریت پست‌ها</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <th>آی دی</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <th>نام کاربر</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <th>پست</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <th>توضیحات</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <th>عملیات</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php while($row = $postsResult->fetch_assoc()): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td><?php echo $row['id']; ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td><?php echo htmlspecialchars($row['username']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  $ext = strtolower(pathinfo($row['media'], PATHINFO_EXTENSION));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if(in_array($ext, ['jpg', 'jpeg', 'png', 'gif'])): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <img src="<?php echo $row['media']; ?>" alt="پست" style="width:50px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <?php elseif(in_array($ext, ['mp4', 'webm', 'ogg'])): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <video width="80" controls>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <source src="<?php echo $row['media']; ?>" type="video/<?php echo $ext; ?>">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </video>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td><?php echo nl2br(htmlspecialchars($row['caption'])); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="admin-panel.php?deletePost=<?php echo $row['id']; ?>" onclick="return confirm('آیا مطمئن هستید؟')">حذف</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function toggleMenu() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              var navLinks = document.querySelector('.nav-links');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      navLinks.classList.toggle('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </html>